name: 'Sync Ansible Automation Platform Projects'
description: 'Sync one or all AAP projects from their source repositories'
inputs:
  ah_host:
    description: 'Automation Hub hostname (e.g., aap.ao.tamu.edu)'
    required: true
  ah_token:
    description: 'Automation Hub API token'
    required: true
  project_name:
    description: 'Specific project name to sync (if empty, syncs all projects)'
    required: false
  sync_timeout:
    description: 'Maximum time in seconds to wait for each project sync to complete'
    required: false
    default: '300'
  sync_poll_interval:
    description: 'Interval in seconds between status checks for project sync'
    required: false
    default: '10'
  sync_retry_attempts:
    description: 'Number of retry attempts if a project sync fails'
    required: false
    default: '3'
  retry_delay:
    description: 'Delay in seconds between retry attempts'
    required: false
    default: '10'
  project_sync_delay:
    description: 'Delay in seconds between starting each project sync (when syncing all projects)'
    required: false
    default: '5'
outputs:
  synced:
    description: 'Whether the project(s) were successfully synced'
runs:
  using: 'node20'
  main: 'index.js'