---
name: ansible-collection-verify

on:
  workflow_call:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify version is bumped
        uses: tamu-edu/ao-workflows/galaxy-version@main
