---
name: ansible-role-verify

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible-lint yamllint

      - name: Lint YAML files
        run: |
          # Create yamllint config if it doesn't exist
          if [ ! -f .yamllint ]; then
            cat > .yamllint << EOF
          ---
          extends: default
          rules:
            line-length:
              max: 120
            comments:
              min-spaces-from-content: 1
            comments-indentation: disable
            truthy:
              allowed-values: ['true', 'false', 'yes', 'no']
          EOF
          fi
          yamllint .
          rm -f .yamllint  # Clean up the config file after linting

      - name: Lint Ansible roles
        run: |
          # Create ansible-lint config if it doesn't exist
          if [ ! -f .ansible-lint ]; then
            cat > .ansible-lint << EOF
          ---
          profile: production
          exclude_paths:
            - .cache/
            - .github/
            - molecule/
            - .ansible-lint
          skip_list:
            - yaml[line-length]  # Handled by yamllint
            - role-name[path]    # Skip galaxy role naming requirements
          EOF
          fi
          ansible-lint
          rm -f .ansible-lint  # Clean up the config file after linting
  
  molecule:
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies if requirements.yml exists
        run: |
          source ~/.bashrc
          conda activate ansible
          if [ -f requirements.yml ]; then
            ansible-galaxy install -r requirements.yml
          else
            echo "No requirements.yml found, skipping dependency installation."
          fi

      - name: Run Molecule tests
        run: |
          source ~/.bashrc
          conda activate ansible
          molecule test --all

      - name: Run Molecule destroy
        if: always()
        run: |
          source ~/.bashrc
          conda activate ansible
          molecule destroy --all || true  # Ensure cleanup even if tests fail
