---
name: ansible-collection-build

on:
  workflow_call:
    secrets:
      galaxy_hub_server:
        description: "The Galaxy Hub server to publish the collection to"
        required: true
      galaxy_hub_token:
        description: "The Galaxy Hub API token for authentication"
        required: true
      token:
        description: "SSH token for accessing private repositories"
        required: true

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.token }}
          submodules: 'recursive'

      
      - name: Build Ansible collection
        run: |
          source ~/.bashrc
          conda activate ansible
          mkdir build
          ansible-galaxy collection build --force --output-path build

      - name: Publish Ansible collection
        run: |
          source ~/.bashrc
          conda activate ansible
          ansible-galaxy collection publish --server ${{ secrets.galaxy_hub_server }} --token ${{ secrets.galaxy_hub_token }} build/*.tar.gz

      - name: Cleanup build artifacts
        if: always()
        run: rm -rf build
