---
name: ansible-collection-build

on:
  workflow_call:
    inputs:
      collection_name:
        description: "The name of the collection to approve"
        required: true
        type: string
      aap_environment:
        description: "Target AAP environment (development or production)"
        required: true
        type: string
      hub_repository:
        description: "The hub repository to publish to (published, staging, etc.)"
        required: false
        type: string
        default: "published"
      op_vault:
        description: "1Password vault name"
        default: "AO-Infrastructure-General"
        type: string
    secrets:
      op_connect_host:
        description: "1Password Connect server URL"
        required: true
      op_connect_token:
        description: "1Password Connect token"
        required: true
      token:
        description: "SSH token for accessing private repositories"
        required: false

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.token || github.token }}
          submodules: ${{ secrets.token && 'recursive' || '' }}

      - name: Load secrets from 1Password
        id: op-load-secret
        uses: 1password/load-secrets-action@v3
        env:
          OP_CONNECT_HOST: ${{ secrets.op_connect_host }}
          OP_CONNECT_TOKEN: ${{ secrets.op_connect_token }}
          AAP_HOSTNAME: op://${{ inputs.op_vault }}/AAP - service account - ${{ inputs.aap_environment }}/hostname
          AAP_HUB_TOKEN: op://${{ inputs.op_vault }}/AAP - service account - ${{ inputs.aap_environment }}/hub_token
          AAP_CONTROLLER_TOKEN: op://${{ inputs.op_vault }}/AAP - service account - ${{ inputs.aap_environment }}/controller_token

      - name: Increment Galaxy Version
        uses: tamu-edu/ao-workflows/increment-galaxy-version@main
        with:
          timezone: 'America/Chicago'

      - name: Build Ansible collection
        run: |
          source ~/.bashrc
          conda activate ansible
          mkdir build
          ansible-galaxy collection build --force --output-path build

      - name: Publish Ansible collection
        run: |
          source ~/.bashrc
          conda activate ansible
          ansible-galaxy collection publish --server https://${{ steps.op-load-secret.outputs.AAP_HOSTNAME }}/api/galaxy/content/${{ inputs.hub_repository }}/ --ignore-certs --token "${{ steps.op-load-secret.outputs.AAP_HUB_TOKEN }}" build/*.tar.gz

      # - name: Push galaxy.yml back to the repository
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     author_name: github-actions
      #     author_email: github-actions@github.com
      #     message: 'Update galaxy.yml version [skip ci]'
      #     add: 'galaxy.yml'
      #     cwd: '.'

      - name: Auto Approve collection
        uses: tamu-edu/ao-workflows/collection-approve@main
        with:
          ah_host: https://${{ steps.op-load-secret.outputs.AAP_HOSTNAME }}
          ah_token: ${{ steps.op-load-secret.outputs.AAP_HUB_TOKEN }}
          namespace: ao_ansible
          name: ${{ inputs.collection_name }}
          timeout: 300
          interval: 10
          ignore_certs: true

      - name: Sync Projects
        uses: tamu-edu/ao-workflows/project-sync@main
        with:
          ah_host: https://${{ steps.op-load-secret.outputs.AAP_HOSTNAME }}
          ah_token: ${{ steps.op-load-secret.outputs.AAP_CONTROLLER_TOKEN }}
          ignore_certs: true

      - name: Cleanup build artifacts
        if: always()
        run: rm -rf build
