---
name: ansible-collection-build

on:
  workflow_call:
    inputs:
      galaxy_hub_server:
        description: "The Galaxy Hub server to publish the collection to"
        required: true
        default: "https://galaxy.ansible.com"
        type: string
      galaxy_hub_token:
        description: "The Galaxy Hub API token for authentication"
        required: true
        type: string

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build Ansible collection
        run: |
          source ~/.bashrc
          conda activate ansible
          mkdir build
          ansible-galaxy collection build --force --output-path build

      - name: Publish Ansible collection
        run: ansible-galaxy collection publish --server ${{ inputs.galaxy_hub_server }} --token ${{ inputs.galaxy_hub_token }} build/*.tar.gz

      - name: Cleanup build artifacts
        if: always()
        run: rm -rf build
