---
name: ansible-collection-build

on:
  workflow_call:
    secrets:
      galaxy_hub_server:
        description: "The Galaxy Hub server to publish the collection to"
        required: true
      galaxy_hub_token:
        description: "The Galaxy Hub API token for authentication"
        required: true
      token:
        description: "SSH token for accessing private repositories"
        required: false

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.token || github.token }}
          submodules: ${{ secrets.token && 'recursive' || '' }}

      - name: Increment Galaxy Version
        uses: tamu-edu/ao-workflows/increment-galaxy-version@main
        with:
          timezone: 'America/Chicago'

      - name: Build Ansible collection
        run: |
          source ~/.bashrc
          conda activate ansible
          mkdir build
          ansible-galaxy collection build --force --output-path build

      - name: Publish Ansible collection
        run: |
          source ~/.bashrc
          conda activate ansible
          ansible-galaxy collection publish --server ${{ secrets.galaxy_hub_server }} --ignore-certs --token ${{ secrets.galaxy_hub_token }} build/*.tar.gz

      # - name: Push galaxy.yml back to the repository
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     author_name: github-actions
      #     author_email: github-actions@github.com
      #     message: 'Update galaxy.yml version [skip ci]'
      #     add: 'galaxy.yml'
      #     cwd: '.'

      - name: Cleanup build artifacts
        if: always()
        run: rm -rf build
